Dorthu/openapi3

- openapi3/object_base.py
- openapi3/openapi.py
- openapi3/paths.py
Features added:
- Cancel ssl verification if requested
- Use session if requested (to perserve cookies, for instance)
- Added the feature of "raw_response" to the request process to address empty responses or responses that are too complicated for the current version of openapi3 code (like those that are based on "allOf")
bug fixes:
- Fixed the lookup of "in_" as it made some stuff fail.
- Added boolean to the types in the lookup so if type is boolean it'll know how to handle it
- Fixed the bug that in case the path held more than one parameter in it, the code would crash.
> Added several new features I needed to openapi3

- openapi3/paths.py
For specifications where the requestBody schema type is an array it was throwing errors. Fix was introduced to support these as well.
> Added possibility to have array of objects in Request

- openapi3/paths.py
Without this, we end up getting an error like this on a content type mismatch, since `err_var` is a tuple, it needs to be arg-expanded into `.format`: 
```
Traceback (most recent call last):
...
File "/path/to/3.7.6/lib/python3.7/site-packages/openapi3/openapi.py", line 189, in __call__
return self.operation(self.base_url, *args, security=self.security,
File "/path/to/3.7.6/lib/python3.7/site-packages/openapi3/paths.py", line 282, in request
raise RuntimeError(err_msg.format(err_var))
IndexError: tuple index out of range
```
> Fix error message formatting.

- openapi3/object_base.py
I know that python2 is end of life, and has been for a little while, but
unfortunately I still need to support it.  As such, this allows unicode
strings in specs to pass validation for `str` types without having to
litter the codebase with references to `unicode`.
> Add support for unicode in python2

- .travis.yml
- README.rst
- openapi3/__init__.py
- setup.py
- tests/conftest.py
- tests/fixtures/README.md
- tests/fixtures/broken-ref.yaml
- tests/fixtures/broken.yaml
- tests/fixtures/petstore-expanded.yaml
- tests/parsing_test.py
- tests/path_test.py
- tests/ref_test.py
This isn't that extensive yet, but this change adds a simple test suite
using pytest which verifies that certain parsing operations, resolution
operations, and failure modes occur.
This still needs:
> Added a simple test suite

- openapi3/object_base.py
- openapi3/openapi.py
- openapi3/schemas.py
- tests/ref_test.py
The allOf construct is described in the spec [here](http://spec.openapis.org/oas/v3.0.3#composition-and-inheritance-polymorphism)
and further [here](https://tools.ietf.org/html/draft-handrews-json-schema-02#section-9.2.1.1).
This change allows for schema composition using the allOf construct.
A schema that defines `allOf` will have all of its attributes merged in
from each schema in the `allOf` in sequence, starting with its default
schema and favoring the schema being merged into it.  For example:
```
components:
schemas:
Example:
type: object
properties:
foo:
type: string
description: Example property
Example2:
allOf:
- $ref: "#/components/schemas/Example"
properties:
foo:
example: bar
```
Would result in a Schema object with a type of "object" and one
property, "foo" whose type is …
> Add support for resolving allOf attributes

- openapi3/paths.py
Right now, if an operationId has spaces in it, there won't be a way to
effectively call it using OpenAPI's `call_{operationId}` dynamic
function (since it would require an invalid function name).
This change replaces spaces with underscores in operationIds when
populating the operation map.  This makes an operationId named "test
operations" called like `spec.call_test_operation`.
> Fix operationIds with spaces when populating operationMap

- .travis.yml
It looks like the module should be installed in travis' virtualenv
before running pytest
> Fix tests in travis

- openapi3/paths.py
- tests/conftest.py
- tests/fixtures/bad-parameter-name.yaml
- tests/parsing_test.py
[The spec says](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.1.0.md#parameter-locations)
that path parameters must actually be part of the operation's URL.
@displague pointed out that this parser was not enforcing that
requirement.  This change begins raising a new SpecError when this
requirement isn't satisfied.
> Validate that parameters defined as in: path exist

- openapi3/openapi.py
- openapi3/paths.py
- tests/conftest.py
- tests/fixtures/dupe-operation-ids.yaml
- tests/parsing_test.py
[The OpenaAPI standard says](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.1.0.md#operation-object)
this about operationId
> Unique string used to identify the operation. The id MUST be unique among all operations described in the API.
@displague reported that this library was not enforcing that
restriction.  This change adds a new SpecError case for when  operationIds
are not unique.
> Don't allow duplicate OperationIDs

- openapi3/paths.py
- tests/conftest.py
- tests/fixtures/parameter-with-underscores.yaml
- tests/parsing_test.py
Hello, and thank you for the `openapi3` library!
In 02cab5b3ad0f41dfcacc0362dab5e393240a9301, a change was made to validate that path parameters are actually in the path. I believe the regex used, `{([a-zA-Z0-9]+)}`, is a bit too restrictive. This means that API endpoints which use `_` in the path names fail with `openapi3 1.2.0` but pass with similar OpenAPI validation tools, such as [`openapi-spec-validator`](https://github.com/p1c2u/openapi-spec-validator).
The OpenAPI3 spec is ambiguous as to what characters are allowed in a path parameter name, as https://github.com/OAI/OpenAPI-Specification/issues/2119 describes in detail. Until that question is unanswered, this commit takes a conservative approach by extending the regex to match the "unreserved" characters of RFC 3986.
I've run …
> Expand path parameter regex

- openapi3/info.py
The [OpenAPI standard](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.1.0.md#contactObject)
requires a Contact object to have all of "name", "url", and "email".
This library was not enforcing those requirements.
This change enforces that all three elements of a Contact field are
required.
> Enforce required fields for Contact element

- openapi3/paths.py
Was this an oversight? The comment was correct.
> Fix Media examples did not handle Example type

- openapi3/paths.py
Attempting to format a path with multiple parameters (e.g. `/{parent_name}/{identifier}`) causes an error response from `format`, since it will only succeed when it can apply to all format arguments in the string.
6b0d17b - 7331206+chrised@users.noreply.github.com
Python's String format method (`format`) does not allow for partial
operation. Strings must be formatted with all required variables
present.
> Allow multiple parameters in a path

- openapi3/schemas.py
The `contentEncoding`, `contentMediaType`, and `contentSchema` field are
defined by JSON Schema [here](https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-validation-00#section-8).
While `contentMediaType` [may be ignored by OpenAPI parsers](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#considerations-for-file-uploads),
its presence should be allowed in case schemas are used by other JSON
Schema applications that are unaware of the OpenAPI context.
This change adds support for all three fields to the Schema type,
allowing schemas that use these fields to pass validation.
> new: Added support for contentEncoding and similar fields

- openapi3/object_base.py
- tests/fixtures/broken.yaml
- tests/parsing_test.py
In making #45, I noticed the validation error was not helpful, and would
be better if it listed out the required fields in the case that only a
single type is allowed.  The old error is still raised in cases where
there are multiple possibilities for a value, since I can't know which
required fields to display, but in the simple case of one specific type
being needed, we can be more helpful.
> Better errors when a single type is required

- openapi3/openapi.py
- openapi3/paths.py
While using this library for testing, I've had to modify aspects to enable compatibility with a semi-mocked requests Session proxy. It would be nice to be able to provide a factory for the session at runtime, and have the resulting session passed into Operations.
d4614bf - 7331206+chrised@users.noreply.github.com
This assists in enabling tests to utilise openapi3 to validate their
local/test endpoints.
2b332da - 7331206+chrised@users.noreply.github.com
If a session is defined at the top level, pass it through to the
Operation class, so that it is used instead of the default session
generated at parse-time.
> Configurable Session Factory & Passthrough to Operations

- openapi3/paths.py
These calls were referencing __class__ instead of self.__class__.
Unfortunately I do still need python2 support
> Fix calls to super in python2

- openapi3/object_base.py
- openapi3/openapi.py
- openapi3/paths.py
- setup.py
- tests/conftest.py
- tests/fixtures/with-securityparameters.yaml
- tests/parsing_test.py
- tests/path_test.py
> Securityparameters

- openapi3/object_base.py
- tests/conftest.py
- tests/fixtures/nested-allOf.yaml
- tests/ref_test.py
I found this while working on https://github.com/linode/linode-cli/pull/218
For a spec fragment like this:
```yaml
schema:
allOf:
- $ref: '#/components/schemas/Example'
- type: object
properties:
foo:
$ref: '#/components/schemas/foo'
bar:
type: array
items:
$ref: '#/components/schemas/bar'
```
neither of the `$ref`s in the second schema in the allOf will be
resolved (the runtime will see each as a Reference type pointing to the
correct part of the schema).
> bug: $refs are not resolved within schemas defined in allOfs

- openapi3/object_base.py
- openapi3/schemas.py
- tests/conftest.py
- tests/fixtures/ref-allof.yaml
- tests/ref_test.py
I found this while working on https://github.com/linode/linode-cli/pull/218
As it happens, a schema fragment like this:
```yaml
paths:
/example:
get:
responses:
'200':
content:
application/json:
schema:
allOf:
- $ref: '#/components/schema/Something'
- type: object
properties:
new:
type: string
```
will incorrectly add the `new` property to the
`components/schemas/Something` schema as it is seen by _all_ references
to it.
> bug: allOfs add additional attributes to referenced schemas

- openapi3/paths.py
- tests/api/main.py
Closes #64
Python's requests library should handle decoding the response for us
using any encoding information included in the Content-type header, so
we can safely ignore it when checking the response against the expected
response types.
> Handle encodings returned in the Content-type header

- openapi3/schemas.py
- tests/conftest.py
- tests/fixtures/schema-without-properties.yaml
- tests/schema_test.py
A Schema defined as:
```
example:
type: object
```
should generate a Model named `example` with no `__slots__`.
This change allows generation of a model as described, and
closes https://github.com/Dorthu/openapi3/issues/70.
> Fixed schemas without properties failing to generate models 

- openapi3/openapi.py
- tests/conftest.py
- tests/fixtures/rfc_6901.yaml
- tests/ref_test.py
> un-escape ~1 and ~0 in paths, handle integers.

- openapi3/example.py
- openapi3/paths.py
- tests/conftest.py
- tests/fixtures/example_array.yaml
- tests/parsing_test.py
Closes #73
The OpenAPI Standard defines a MediaType.example as [any type](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#media-type-object),
and similarly for [Example.value](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#example-object).
This library previously did not implement these types in that way,
instead accepting a broad set of types, but not _actually_ any type -
namely, arrays would break since they are handled specially when parsing
the spec.
This change moves to `"*"` as the accepted type, which is handled as the
special-case "any" type when parsing specs.  This results in the
expected behavior.  A test was added to confirm that arrays are accepted
as expected.
> bug: Accept "any" type for Example values

- openapi3/__init__.py
- openapi3/errors.py
- openapi3/paths.py
- tests/api/main.py
- tests/fastapi_test.py
Closes #80
When this library is used as a client and the server returns a response
that was not declared in the operation's responses, an exception is
raised.  Right now, this is a `RuntimeError` with a message explaining
what code was returned, and that it was undocumented.  This is not
useful when using the client against an API whose documentation you do
not control, and that is missing exhaustive documentation for responses
(generally error responses fall into this category).
This change adds a new error type, `openapi3.UnexpectedResponseError`,
and raises that instead of `RuntimeError`.  In addition to the message,
this error includes the full response that was returned, the operation
that made the call, and the status code that was not expected. This new
error is a subclass of …
> bug: Use custom error class for undeclared responses

- openapi3/paths.py
Fixes : https://github.com/Dorthu/openapi3/issues/47
`verify` parameter was not being honoured.
> bugfix: honour verify field in request

- openapi3/info.py
- tests/conftest.py
- tests/fixtures/empty_contact.yaml
- tests/parsing_test.py
Closes #82
The definition of the [Contact object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.0.md#contact-object)
does not list any required fields; these were marked as required my
mistake.
> bug: Fields of Contact are not required

- openapi3/components.py
- openapi3/general.py
- openapi3/object_base.py
- openapi3/openapi.py
- tests/conftest.py
- tests/fixtures/openapi-3.1.0-refs.yaml
- tests/path_test.py
- tests/ref_test.py
Closes #61
In OpenAPI 3.1.0, the [Reference Object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#reference-object) gained two new attributes, `summary` and `description`.  These attributes are optional, and #61 indicated that they were preventing this library from parsing specs where they were present.
Based on the standard, these fields are ignored unless the referenced type has a like-named field; in that case only, the value in the Reference Object's fields are used in place of that values in the like-named fields of the object it references. For example, in this partial spec:
```yaml
paths:
/example:
$ref: '#/components/pathItems/example'
summary: Override
components:
pathItems:
example:
summary: Original
```
The value of `paths./example.summary` should be …
> Support OpenAPI 3.1.0 extended Reference objects

- openapi3/openapi.py
- tests/conftest.py
- tests/fixtures/reference-reference-reference.yaml
- tests/ref_test.py
Related to https://github.com/linode/linode-cli/pull/423
In the above, it was discovered that a reference in a `requestBody`
schema that references a reference in `components.schema` will see the
`Reference` object once resolution is complete, which is unexpected; it
should see the final `Schema`.
This change resolves all references in `components` before resolving
them in the rest of the spec to ensure they are always done in the
proper order.
> bug: Resolve references in components first

- openapi3/schemas.py
- tests/conftest.py
- tests/fixtures/with_all_default_types.yaml
- tests/parsing_test.py
Closes #91
It looks like I missed the [number type](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#data-types) initially, so floating-point values weren't being parsed correctly.  This change adds support for them, and also adds a test to ensure that all `types` values in a schema can correctly parse their corrosponding `default` value.
> bug: Correctly parse all types for `default`

- openapi3/schemas.py
- tests/conftest.py
- tests/fixtures/merge-extension.yaml
- tests/ref_test.py
This change adds support for merging extensions through the [Schema._merge(...)](https://github.com/Dorthu/openapi3/blob/master/openapi3/schemas.py#LL204C1-L204C1) method and adds a corresponding test.
This change addresses an issue that caused the [x-linode-cli-format extension](https://github.com/linode/linode-api-docs/blob/development/openapi.yaml#LL20854C1-L20854C13) to not be inherited in the [Firewall Rules Update](https://github.com/linode/linode-api-docs/blob/development/openapi.yaml#L13533) and the [Firewall Create](https://github.com/linode/linode-api-docs/blob/development/openapi.yaml#L12988) endpoints.
Please let me know if you have any feedback :slightly_smiling_face:
> fix: Support extensions when merging references

- openapi3/schemas.py
- tests/conftest.py
- tests/fixtures/deeply-nested-allOf.yaml
- tests/ref_test.py
This change updates the `Schema.resolve_allOfs()` override to recursively resolve `allOfs` for all children objects. This is necessary as allOfs would not previously be parsed in nested Schema objects.
For example, [this segment](https://github.com/linode/linode-api-docs/blob/development/openapi.yaml#L6408-L6413) from the Linode OpenAPI spec would not be parsed correctly because it is nested in `properties.automatic.items`.
> fix: Recursively resolve allOfs for schema objects
